### ISSUE TITLE
What were you trying to achieve?

### ISSUE THREAD

**Issue by rosacola** [fake-name/DanbooruScraper#1]
I can think of automatic image tagging. What was the outcome? What is the status of this project?

**Comment by fake-name** [comment]
The idea was basically to replicate the [google deep dream neural net thing](https://en.wikipedia.org/wiki/DeepDream), only with a training dataset of hentai. The end result being automatic generation of possibly the worst porn possible.

The project stalled at the neural net stage, due to the fact that my friend who was going to do the machine learning end didn't get around to it, and I have too many projects to take the time.
